/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DoctorId = IDL.Nat;
export const DepartmentId = IDL.Nat;
export const TimeSlot = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
});
export const AppointmentRequest = IDL.Record({
  'doctorId' : DoctorId,
  'patientEmail' : IDL.Text,
  'date' : IDL.Text,
  'patientPhone' : IDL.Text,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'departmentId' : DepartmentId,
  'timeSlot' : TimeSlot,
});
export const AppointmentId = IDL.Nat;
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'patientEmail' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'patientPhone' : IDL.Text,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'departmentId' : DepartmentId,
  'timeSlot' : TimeSlot,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'availableEquipment' : IDL.Vec(IDL.Text),
  'keyTreatments' : IDL.Vec(IDL.Text),
});
export const ConsultationHours = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'days' : IDL.Text,
});
export const Doctor = IDL.Record({
  'id' : DoctorId,
  'bio' : IDL.Text,
  'yearsOfExperience' : IDL.Nat,
  'consultationHours' : ConsultationHours,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'imageUrl' : IDL.Text,
  'consultationFee' : IDL.Nat,
  'qualification' : IDL.Text,
  'departmentId' : DepartmentId,
});
export const WorkingHours = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'days' : IDL.Text,
});
export const HospitalInfo = IDL.Record({
  'about' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'totalBeds' : IDL.Nat,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'workingHours' : IDL.Vec(WorkingHours),
  'establishedYear' : IDL.Nat,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
  'emergencyPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func([AppointmentRequest], [Appointment], []),
  'cancelAppointment' : IDL.Func([AppointmentId], [IDL.Bool], []),
  'getAppointment' : IDL.Func(
      [AppointmentId],
      [IDL.Opt(Appointment)],
      ['query'],
    ),
  'getAvailableTimeSlots' : IDL.Func(
      [DoctorId, IDL.Text],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(Doctor)], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getDoctorsByDepartment' : IDL.Func(
      [DepartmentId],
      [IDL.Vec(Doctor)],
      ['query'],
    ),
  'getHospitalInfo' : IDL.Func([], [HospitalInfo], ['query']),
  'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DoctorId = IDL.Nat;
  const DepartmentId = IDL.Nat;
  const TimeSlot = IDL.Record({ 'startTime' : IDL.Text, 'endTime' : IDL.Text });
  const AppointmentRequest = IDL.Record({
    'doctorId' : DoctorId,
    'patientEmail' : IDL.Text,
    'date' : IDL.Text,
    'patientPhone' : IDL.Text,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'departmentId' : DepartmentId,
    'timeSlot' : TimeSlot,
  });
  const AppointmentId = IDL.Nat;
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : AppointmentStatus,
    'doctorId' : DoctorId,
    'patientEmail' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'patientPhone' : IDL.Text,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'departmentId' : DepartmentId,
    'timeSlot' : TimeSlot,
  });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'availableEquipment' : IDL.Vec(IDL.Text),
    'keyTreatments' : IDL.Vec(IDL.Text),
  });
  const ConsultationHours = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'days' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'id' : DoctorId,
    'bio' : IDL.Text,
    'yearsOfExperience' : IDL.Nat,
    'consultationHours' : ConsultationHours,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'imageUrl' : IDL.Text,
    'consultationFee' : IDL.Nat,
    'qualification' : IDL.Text,
    'departmentId' : DepartmentId,
  });
  const WorkingHours = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'days' : IDL.Text,
  });
  const HospitalInfo = IDL.Record({
    'about' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'totalBeds' : IDL.Nat,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'workingHours' : IDL.Vec(WorkingHours),
    'establishedYear' : IDL.Nat,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
    'emergencyPhone' : IDL.Text,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func([AppointmentRequest], [Appointment], []),
    'cancelAppointment' : IDL.Func([AppointmentId], [IDL.Bool], []),
    'getAppointment' : IDL.Func(
        [AppointmentId],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'getAvailableTimeSlots' : IDL.Func(
        [DoctorId, IDL.Text],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(Doctor)], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getDoctorsByDepartment' : IDL.Func(
        [DepartmentId],
        [IDL.Vec(Doctor)],
        ['query'],
      ),
    'getHospitalInfo' : IDL.Func([], [HospitalInfo], ['query']),
    'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };