/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'patientEmail' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'patientPhone' : string,
  'notes' : string,
  'patientName' : string,
  'departmentId' : DepartmentId,
  'timeSlot' : TimeSlot,
}
export type AppointmentId = bigint;
export interface AppointmentRequest {
  'doctorId' : DoctorId,
  'patientEmail' : string,
  'date' : string,
  'patientPhone' : string,
  'notes' : string,
  'patientName' : string,
  'departmentId' : DepartmentId,
  'timeSlot' : TimeSlot,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface ConsultationHours {
  'startTime' : string,
  'endTime' : string,
  'days' : string,
}
export interface Department {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'iconName' : string,
  'availableEquipment' : Array<string>,
  'keyTreatments' : Array<string>,
}
export type DepartmentId = bigint;
export interface Doctor {
  'id' : DoctorId,
  'bio' : string,
  'yearsOfExperience' : bigint,
  'consultationHours' : ConsultationHours,
  'name' : string,
  'specialty' : string,
  'imageUrl' : string,
  'consultationFee' : bigint,
  'qualification' : string,
  'departmentId' : DepartmentId,
}
export type DoctorId = bigint;
export interface HospitalInfo {
  'about' : string,
  'city' : string,
  'name' : string,
  'totalBeds' : bigint,
  'email' : string,
  'website' : string,
  'workingHours' : Array<WorkingHours>,
  'establishedYear' : bigint,
  'state' : string,
  'address' : string,
  'phone' : string,
  'pincode' : string,
  'emergencyPhone' : string,
}
export interface TimeSlot { 'startTime' : string, 'endTime' : string }
export type Timestamp = bigint;
export interface WorkingHours {
  'startTime' : string,
  'endTime' : string,
  'days' : string,
}
export interface _SERVICE {
  'bookAppointment' : ActorMethod<[AppointmentRequest], Appointment>,
  'cancelAppointment' : ActorMethod<[AppointmentId], boolean>,
  'getAppointment' : ActorMethod<[AppointmentId], [] | [Appointment]>,
  'getAvailableTimeSlots' : ActorMethod<[DoctorId, string], Array<TimeSlot>>,
  'getDepartment' : ActorMethod<[bigint], [] | [Department]>,
  'getDepartments' : ActorMethod<[], Array<Department>>,
  'getDoctor' : ActorMethod<[DoctorId], [] | [Doctor]>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getDoctorsByDepartment' : ActorMethod<[DepartmentId], Array<Doctor>>,
  'getHospitalInfo' : ActorMethod<[], HospitalInfo>,
  'listAppointments' : ActorMethod<[], Array<Appointment>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];