/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Department {
    id: bigint;
    name: string;
    description: string;
    iconName: string;
    availableEquipment: Array<string>;
    keyTreatments: Array<string>;
}
export type Timestamp = bigint;
export interface TimeSlot {
    startTime: string;
    endTime: string;
}
export interface ConsultationHours {
    startTime: string;
    endTime: string;
    days: string;
}
export type DoctorId = bigint;
export interface HospitalInfo {
    about: string;
    city: string;
    name: string;
    totalBeds: bigint;
    email: string;
    website: string;
    workingHours: Array<WorkingHours>;
    establishedYear: bigint;
    state: string;
    address: string;
    phone: string;
    pincode: string;
    emergencyPhone: string;
}
export type DepartmentId = bigint;
export interface Doctor {
    id: DoctorId;
    bio: string;
    yearsOfExperience: bigint;
    consultationHours: ConsultationHours;
    name: string;
    specialty: string;
    imageUrl: string;
    consultationFee: bigint;
    qualification: string;
    departmentId: DepartmentId;
}
export interface AppointmentRequest {
    doctorId: DoctorId;
    patientEmail: string;
    date: string;
    patientPhone: string;
    notes: string;
    patientName: string;
    departmentId: DepartmentId;
    timeSlot: TimeSlot;
}
export type AppointmentId = bigint;
export interface WorkingHours {
    startTime: string;
    endTime: string;
    days: string;
}
export interface Appointment {
    id: AppointmentId;
    status: AppointmentStatus;
    doctorId: DoctorId;
    patientEmail: string;
    date: string;
    createdAt: Timestamp;
    patientPhone: string;
    notes: string;
    patientName: string;
    departmentId: DepartmentId;
    timeSlot: TimeSlot;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export interface backendInterface {
    bookAppointment(req: AppointmentRequest): Promise<Appointment>;
    cancelAppointment(id: AppointmentId): Promise<boolean>;
    getAppointment(id: AppointmentId): Promise<Appointment | null>;
    getAvailableTimeSlots(doctorId: DoctorId, date: string): Promise<Array<TimeSlot>>;
    getDepartment(id: bigint): Promise<Department | null>;
    getDepartments(): Promise<Array<Department>>;
    getDoctor(id: DoctorId): Promise<Doctor | null>;
    getDoctors(): Promise<Array<Doctor>>;
    getDoctorsByDepartment(departmentId: DepartmentId): Promise<Array<Doctor>>;
    getHospitalInfo(): Promise<HospitalInfo>;
    listAppointments(): Promise<Array<Appointment>>;
}
import type { Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentStatus as _AppointmentStatus, Department as _Department, DepartmentId as _DepartmentId, Doctor as _Doctor, DoctorId as _DoctorId, TimeSlot as _TimeSlot, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookAppointment(arg0: AppointmentRequest): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: AppointmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async getAppointment(arg0: AppointmentId): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTimeSlots(arg0: DoctorId, arg1: string): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0, arg1);
            return result;
        }
    }
    async getDepartment(arg0: bigint): Promise<Department | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartment(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartment(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartments();
            return result;
        }
    }
    async getDoctor(arg0: DoctorId): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return result;
        }
    }
    async getDoctorsByDepartment(arg0: DepartmentId): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorsByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorsByDepartment(arg0);
            return result;
        }
    }
    async getHospitalInfo(): Promise<HospitalInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalInfo();
            return result;
        }
    }
    async listAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    status: _AppointmentStatus;
    doctorId: _DoctorId;
    patientEmail: string;
    date: string;
    createdAt: _Timestamp;
    patientPhone: string;
    notes: string;
    patientName: string;
    departmentId: _DepartmentId;
    timeSlot: _TimeSlot;
}): {
    id: AppointmentId;
    status: AppointmentStatus;
    doctorId: DoctorId;
    patientEmail: string;
    date: string;
    createdAt: Timestamp;
    patientPhone: string;
    notes: string;
    patientName: string;
    departmentId: DepartmentId;
    timeSlot: TimeSlot;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n3(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientEmail: value.patientEmail,
        date: value.date,
        createdAt: value.createdAt,
        patientPhone: value.patientPhone,
        notes: value.notes,
        patientName: value.patientName,
        departmentId: value.departmentId,
        timeSlot: value.timeSlot
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
